/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.hotel.pages;

import com.hotel.classes.ChartBarra;
import com.hotel.classes.ChartLinear;
import com.hotel.classes.ChartPizza;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Caio
 */
public class TelaChooseReport extends javax.swing.JFrame {
    private ChartPanel chartPanel;
    private JFreeChart chart;
    /**
     * Creates new form TelaChooseReport
     */
    public TelaChooseReport() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1424721748_f-table-row_128-64.png"))); // NOI18N
        jButton1.setText("TABELA");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1424721801_Bar-chart.png"))); // NOI18N
        jButton2.setText("BARRA");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1424721840_web-space-px-png.png"))); // NOI18N
        jButton3.setText("PIZZA");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1424721890_line-chart-64.png"))); // NOI18N
        jButton4.setText("LINEAR");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        acao3();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        acao();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        acao2();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    
    private void acao3(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.addValue(212, "Classes", "JDK 1.0");
        dataset.addValue(504, "Classes", "JDK 1.1");
        dataset.addValue(1520, "Classes", "SDK 1.2");
        dataset.addValue(1842, "Classes", "SDK 1.3");
        dataset.addValue(2991, "Classes", "SDK 1.4");
        
        chartPanel = ChartLinear.createAChartPanelComplete(new java.awt.Dimension(300, 300), 
                dataset, 
                "TITULO", 
                "SUBTITULO AQUI BEM AQUI",
                "Footer e agradecimento colocado bem aqui.", 
                "DOMINIO", "IMAGEM", PlotOrientation.VERTICAL, true, true, false);
        ChartLinear.createAJframe(chartPanel, null).setVisible(true);

    }
    
    private void acao2(){
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("FECHADOS", 1);
        pieDataset.setValue("REJEITADOS", 2);
        pieDataset.setValue("PENDENTES", 3);
        pieDataset.setValue("SOS", 4);
        pieDataset.setValue("Fidelidade em outra operadora", 2);
        pieDataset.setValue("Satisfeito Concorrencia", 4);
        pieDataset.setValue("Cliente GVT Satisfeito", 2);
        pieDataset.setValue("Numero Inexistente", 1);
        
        this.chartPanel = ChartPizza.createAChartPanelComplete3D(new java.awt.Dimension(300,300), pieDataset, "TITULO", true, true,false);
        ChartPizza.createAJframe(chartPanel, null).setVisible(true);
    }
    
    private void acao(){
        DefaultCategoryDataset data = new DefaultCategoryDataset();
        data.setValue(1, "Op1", "C1");
        data.setValue(2, "Op2", "C1");
        data.setValue(3, "Op3", "C1");
        data.setValue(4, "Op4", "C1");
        data.setValue(5, "Op5", "C1");
        data.setValue(3, "Op6", "C1");
        this.chartPanel = ChartBarra.createAChartPanelComplete3D(new java.awt.Dimension(500, 500), data, "TITULO", "DOMINIO", "VALORES", PlotOrientation.VERTICAL, true, true, false);
        ChartBarra.createAJframe(chartPanel, null).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
